.catalog:
  name: G-WAN-static
  version: 7.5
  description: |
      G-wan static provisioned from Git repo
  uuid: g-wan-static-0
  questions:
    - variable: "exo-scale1"
      description: "Number of exosphere nodes."
      label: "Number of Exosphere Nodes:"
      required: true
      default: 1
      type: "int"
